---
title: "State of Open Data"
author: "Laurence Horton"
date: "12/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.fullwidth=TRUE, echo = FALSE, warning = FALSE, message = FALSE)
```

## Download data

Research, Nature; Goodey, Greg (2021): State of Open Data Survey 2021 additional resources. figshare. Dataset. https://doi.org/10.6084/m9.figshare.17081231.v1
```{r download 2016-2021 data file}
download.file("https://figshare.com/ndownloader/articles/17081231/versions/1", basename("sod.zip"))
unzip("sod.zip")
```

Remove zip
```{r remove zip file}
unlink("sod.zip", recursive = TRUE)
```

Library
```{r library, include = FALSE}
library(tidyverse)
library(readxl) # For reading in excel files
library(scales) # For graphics breaks and labels
library(knitr) # For tables
```

## Read in data
```{r read in data}
sod <- read_excel("State of Open Data 2021_Master data_cleaned.xlsx")
```

## Clean data
Remove first row that contains column names
```{r remove first row with column names}
sod <- sod[-1,] # remove first row names.
```

ASCII stuff
```{r ASCII}
sod <- as.data.frame(apply(sod, 2, function(sod) gsub("&amp;", "and", sod)))
sod <- as.data.frame(apply(sod, 2, function(sod) gsub("&", "and", sod)))
sod <- as.data.frame(apply(sod, 2, function(sod) gsub("’", "'", sod)))
sod <- as.data.frame(apply(sod, 2, function(sod) str_trim(sod)))
```

Standardize responses
```{r Q2.8 Standardise responses}
#Q2.8
sod$Q2.8 <- gsub("data principles", "principles", sod$Q2.8)
sod$Q2.8 <- gsub("I'm", "I am", sod$Q2.8)
sod$Q2.8 <- gsub("I've", "I have", sod$Q2.8)
```

```{r Q3.1 Standardise responses}
#Q3.1
sod$Q3.1 <- gsub("its", "it's", sod$Q3.1)
sod$Q3.1 <- gsub(" ,", ",", sod$Q3.1)
sod$Q3.1 <- gsub("of the data collected", "", sod$Q3.1)
sod$Q3.1 <- gsub(" collected", "", sod$Q3.1)
sod$Q3.1 <- gsub("\\:", "", sod$Q3.1)
sod$Q3.1 <- gsub("we would", "would", sod$Q3.1)
sod$Q3.1 <- gsub("some data", "some", sod$Q3.1)
sod$Q3.1 <- gsub("some ", "some", sod$Q3.1)
```

```{r Q3.6 Standardise responses}
#Q3.6
sod$Q3.6 <- gsub("those no", "not", sod$Q3.6)
sod$Q3.6 <- gsub("ie ", "i.e. ", sod$Q3.6)
sod$Q3.6 <- gsub("My own funds", "Own funds", sod$Q3.6)
sod$Q3.6 <- gsub("Your institution/organisation", "Your institution", sod$Q3.6)
sod$Q3.6 <- gsub("\\(", "", sod$Q3.6)
sod$Q3.6 <- gsub("\\)", "", sod$Q3.6)
sod$Q3.6 <- gsub("Funds identified in your grant for this purpose", "Funds identified in grant for this purpose", sod$Q3.6)
```

```{r Q3.7 Standardise responses}
# Q3.7
sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("Web search", "Web-search", sod))
                                       }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("0Research", "Research", sod))
                                 }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(
                                           gsub(
                                             "Institutional expertise",
                                             "institutional expertise",
                                             sod))
                                       }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("Research office", "	
Research office/In-house institutional expertise", sod))
                                       }))


sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(
                                           gsub(
                                             " \\/ ",
                                             "\\/",
                                             sod))
                                       }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(
                                           gsub(
                                             "In-house Institutional expertise Research office",
                                             "Research office\\/In-house institutional expertise",
                                             sod))
                                       }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(
                                           gsub(
                                             "In-house institutional expertise",
                                             "Research office\\/In-house institutional expertise",
                                             sod))
                                       }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("3rd-party", "3rd party", sod))
                                 }))
sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("party service", "party", sod))
                                 }))
sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("Other \\(please specify\\)", "Other", sod))}))
sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("Institutional Library", "Library", sod))
                                 }))
sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("expertise 0", "expertise", sod))
                                 }))
sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("Colleague/Supervisor", "Colleague", sod))
                                 }))
	
sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("Research office/Research office/In-house institutional expertise/Research office/In-house institutional expertise", "Research office/In-house institutional expertise", sod))
                                 }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("Research office/Research office/In-house institutional expertise", "Research office/In-house institutional expertise", sod))
                                 }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("Research office/In-house institutional expertise 	Research office/Research office/In-house institutional expertise", "Research office/In-house institutional expertise", sod))
                                 }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("\r?\n|\r", "", sod))
                                 }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub("\r?\t|\r", "", sod))
                                 }))

sod[, c(41:51)] <- as.data.frame(apply(sod[, c(41:51)], 2,
                                       function(sod) {
                                         as.character(gsub(" Research office/In-house institutional expertise", "", sod))
                                 }))

sod$Q3.7_7 <-
  sod$Q3.7_7[sod$Q3.7_7 == "00"] <- "0"
```


```{r Q3.10 Standardise responses}
# Q3.10
sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("Contain sensitive information or require permissions before sharing", "Contain sensitive information", sod))
                                       }))

sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("Contains sensitive information or require study participant permissions before sharing", "Contain sensitive information", sod))
                                       }))

sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("Unsure about copyright and data licensing", "Unsure about copyright licensing", sod))
                                       }))

sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("Unsure about copyright and licensing", "Unsure about copyright licensing", sod))
                                       }))

sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("I do not know what repository to use", "Not know what repository to use", sod))
                                       }))

sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("Not knowing which repository to use", "Not know what repository to use", sod))
                                       }))

sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("I am unsure I have permission from my funder or institute to share my data", "Unsure I have the permission to share", sod))
                                       }))

sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("Unsure I have the rights to share", "Unsure I have the permission to share", sod))
                                       }))

sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("Concerns about misuse of my data", "Concerns about misuse of data", sod))
                                       }))

sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("Not receiving appropriate credit or knowledge", "Not receiving appropriate credit or acknowledgement", sod))
                                       }))

sod[, c(65:83)] <- as.data.frame(apply(sod[, c(65:83)], 2,
                                       function(sod) {
                                         as.character(gsub("I have no desire to share data", "I have no desire to share my data", sod))
                                       }))
```

```{r Q3.12 Standardise responses}
# Q3.12
sod[, c(87:94)] <- as.data.frame(apply(sod[, c(87:94)], 2,
                                       function(sod) {
                                         as.character(gsub("Copyright\\/ licensing of data", "Copyright\\/Licensing of data", sod))
                                       }))

sod[, c(87:94)] <- as.data.frame(apply(sod[, c(87:94)], 2,
                                       function(sod) {
                                         as.character(gsub("Copyright\\/Licencing of data", "Copyright\\/Licensing of data", sod))
                                       }))

sod[, c(87:94)] <- as.data.frame(apply(sod[, c(87:94)], 2,
                                       function(sod) {
                                         as.character(gsub("Copyright\\/licensing of data", "Copyright\\/Licensing of data", sod))
                                       }))

sod[, c(87:94)] <- as.data.frame(apply(sod[, c(87:94)], 2,
                                       function(sod) {
                                         as.character(gsub("Creating time to manage activity", "Finding the time to manage my data", sod))
                                       }))

sod[, c(87:94)] <- as.data.frame(apply(sod[, c(87:94)], 2,
                                       function(sod) {
                                         as.character(gsub("Data management plans", "Data Management Plans", sod))
                                       }))

sod$Q3.12_3 <-
  sod$Q3.12_3[sod$Q3.12_3 == "Copyright / licensing of data"] <- "Copyright/Licensing of data"
```

```{r Q4.3 standerdise responses}
sod[, c(106:111)] <- as.data.frame(apply(sod[, c(106:111)], 2, function(sod) { as.character(gsub("Avoid duplication of effort", "Avoids duplication of effort", sod))}))

sod[, c(106:111)] <- as.data.frame(apply(sod[, c(106:111)], 2, function(sod) { as.character(gsub("Complement existing data I have collected", "Complement existing data collected", sod))}))

sod[, c(106:111)] <- as.data.frame(apply(sod[, c(106:111)], 2, function(sod) { as.character(gsub("Complements existing data I have collected", "Complement existing data collected", sod))}))

sod[, c(106:111)] <- as.data.frame(apply(sod[, c(106:111)], 2, function(sod) { as.character(gsub("Complements existing data you have collected", "Complement existing data collected", sod))}))

sod[, c(106:111)] <- as.data.frame(apply(sod[, c(106:111)], 2, function(sod) { as.character(gsub("Foster collaboration", "Fosters collaboration", sod))}))

sod[, c(106:111)] <- as.data.frame(apply(sod[, c(106:111)], 2, function(sod) { as.character(gsub("I hasn't/would not benefit me", "It has not or would not benefit me", sod))}))

sod[, c(106:111)] <- as.data.frame(apply(sod[, c(106:111)], 2, function(sod) { as.character(gsub("It hasn't/would not benefit me", "It has not or would not benefit me", sod))}))

sod[, c(106:111)] <- as.data.frame(apply(sod[, c(106:111)], 2, function(sod) {
 as.character(gsub("Validate my own research findings", "Validates own findings", sod))}))

sod[, c(106:111)] <- as.data.frame(apply(sod[, c(106:111)], 2, function(sod) {
 as.character(gsub("Validates my own research findings", "Validates own findings", sod))}))
```

```{r Q5.2 and 5.3 standardise responses}
sod[, c(161:180)] <- as.data.frame(apply(sod[, c(161:180)], 2, function(sod) { as.character(gsub("Direct request from other researcher", "Direct request from another research", sod))}))

sod[, c(161:180)] <- as.data.frame(apply(sod[, c(161:180)], 2, function(sod) { as.character(gsub("Greater transparency and reuse", "Transparency and re-use", sod))}))

sod[, c(161:180)] <- as.data.frame(apply(sod[, c(161:180)], 2, function(sod) { as.character(gsub("Institution\\/organisation requirement", "Institution or Organisation requirement", sod))}))

sod[, c(161:180)] <- as.data.frame(apply(sod[, c(161:180)], 2, function(sod) { as.character(gsub("Institution\\/Organisation requirement", "Institution or Organisation requirement", sod))}))

sod[, c(161:180)] <- as.data.frame(apply(sod[, c(161:180)], 2, function(sod) { as.character(gsub("Institution\\/organization requirement", "Institution or Organisation requirement", sod))}))

sod[, c(161:180)] <- as.data.frame(apply(sod[, c(161:180)], 2,
 function(sod) { as.character(gsub("It was made easy and simple to do so", "It was made simple and easy to do", sod))}))

sod[, c(161:180)] <- as.data.frame(apply(sod[, c(161:180)], 2, function(sod) { as.character(gsub("It was made simple and easy to do so", "It was made simple and easy to do", sod))}))

sod[, c(161:180)] <- as.data.frame(apply(sod[, c(161:180)], 2, function(sod) { as.character(gsub("Journal\\/publisher requirement", "Journal or Publisher requirement", sod))}))

sod[, c(161:180)] <- as.data.frame(apply(sod[, c(161:180)], 2, function(sod) { as.character(gsub("Journal\\/Publisher requirement", "Journal or Publisher requirement", sod))}))
```

```{r Q5.6 standardise responses}
sod[, c(184:191)] <- as.data.frame(apply(sod[, c(184:191)], 2, function(sod) { as.character(gsub("data sharing", "actions", sod))}))

sod[, c(184:191)] <- as.data.frame(apply(sod[, c(184:191)], 2, function(sod) { as.character(gsub("my actions", "actions", sod))}))

sod[, c(184:191)] <- as.data.frame(apply(sod[, c(184:191)], 2, function(sod) { as.character(gsub("Considerations", " Consideration", sod))}))

sod$Q5.6_5 <-
  sod$Q5.6_5[sod$Q5.6_5 == " Consideration of actions in a grant application"] <- "Consideration of actions in a grant application"
```

```{r Q6.1 standardise responses}
sod$Q6.1 <- gsub("Government \\/ Local government", "Government\\/Local government", sod$Q6.1)
sod$Q6.1 <- gsub("Government\\/local government", "Government\\/Local government", sod$Q6.1)
sod$Q6.1 <- gsub("Medical School", "Medical school", sod$Q6.1)
sod$Q6.1 <- gsub(":", "", sod$Q6.1)
```

Make survey year numeric
```{r make survey year numeric}
sod$Survey <- as.numeric(as.character(sod$Survey))
sod$Q2.3 <- as.numeric(as.character(sod$Q2.3))
```